#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC1B74D5998A5F657 (jens@plyp.com)
#
Name     : pypi-zope.security
Version  : 6.0
Release  : 69
URL      : https://files.pythonhosted.org/packages/71/37/ae1f7c0fe867a903af1ccd9eaa933b6a09436ca02305c789bd689fb7fe29/zope.security-6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/71/37/ae1f7c0fe867a903af1ccd9eaa933b6a09436ca02305c789bd689fb7fe29/zope.security-6.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/71/37/ae1f7c0fe867a903af1ccd9eaa933b6a09436ca02305c789bd689fb7fe29/zope.security-6.0.tar.gz.asc
Summary  : Zope Security Framework
Group    : Development/Tools
License  : ZPL-2.1
Requires: pypi-zope.security-filemap = %{version}-%{release}
Requires: pypi-zope.security-lib = %{version}-%{release}
Requires: pypi-zope.security-license = %{version}-%{release}
Requires: pypi-zope.security-python = %{version}-%{release}
Requires: pypi-zope.security-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(zope.component)
BuildRequires : pypi(zope.i18nmessageid)
BuildRequires : pypi(zope.interface)
BuildRequires : pypi(zope.location)
BuildRequires : pypi(zope.proxy)
BuildRequires : pypi(zope.schema)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===================
``zope.security``
===================
.. image:: https://github.com/zopefoundation/zope.security/actions/workflows/tests.yml/badge.svg
:target: https://github.com/zopefoundation/zope.security/actions/workflows/tests.yml

%package filemap
Summary: filemap components for the pypi-zope.security package.
Group: Default

%description filemap
filemap components for the pypi-zope.security package.


%package lib
Summary: lib components for the pypi-zope.security package.
Group: Libraries
Requires: pypi-zope.security-license = %{version}-%{release}
Requires: pypi-zope.security-filemap = %{version}-%{release}

%description lib
lib components for the pypi-zope.security package.


%package license
Summary: license components for the pypi-zope.security package.
Group: Default

%description license
license components for the pypi-zope.security package.


%package python
Summary: python components for the pypi-zope.security package.
Group: Default
Requires: pypi-zope.security-python3 = %{version}-%{release}

%description python
python components for the pypi-zope.security package.


%package python3
Summary: python3 components for the pypi-zope.security package.
Group: Default
Requires: pypi-zope.security-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(zope.security)
Requires: pypi(setuptools)
Requires: pypi(zope.component)
Requires: pypi(zope.i18nmessageid)
Requires: pypi(zope.interface)
Requires: pypi(zope.location)
Requires: pypi(zope.proxy)
Requires: pypi(zope.schema)

%description python3
python3 components for the pypi-zope.security package.


%prep
%setup -q -n zope.security-6.0
cd %{_builddir}/zope.security-6.0
pushd ..
cp -a zope.security-6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1673893552
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-zope.security
cp %{_builddir}/zope.security-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-zope.security/a0b53f43aab58b46bf79ba756c50771c605ab4c5 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-zope.security

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-zope.security/a0b53f43aab58b46bf79ba756c50771c605ab4c5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
