#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-zope.security
Version  : 5.4
Release  : 62
URL      : https://files.pythonhosted.org/packages/b6/fb/65f1b37ef5ad66871b86d7a4aab6f51efd6e56ac09dda34c97b007b00928/zope.security-5.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/b6/fb/65f1b37ef5ad66871b86d7a4aab6f51efd6e56ac09dda34c97b007b00928/zope.security-5.4.tar.gz
Summary  : Zope Security Framework
Group    : Development/Tools
License  : ZPL-2.1
Requires: pypi-zope.security-filemap = %{version}-%{release}
Requires: pypi-zope.security-lib = %{version}-%{release}
Requires: pypi-zope.security-license = %{version}-%{release}
Requires: pypi-zope.security-python = %{version}-%{release}
Requires: pypi-zope.security-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(zope.component)
BuildRequires : pypi(zope.i18nmessageid)
BuildRequires : pypi(zope.interface)
BuildRequires : pypi(zope.location)
BuildRequires : pypi(zope.proxy)
BuildRequires : pypi(zope.schema)

%description
===============
zope.security
===============
.. image:: https://img.shields.io/pypi/v/zope.security.svg
:target: https://pypi.python.org/pypi/zope.security/
:alt: Latest release

%package filemap
Summary: filemap components for the pypi-zope.security package.
Group: Default

%description filemap
filemap components for the pypi-zope.security package.


%package lib
Summary: lib components for the pypi-zope.security package.
Group: Libraries
Requires: pypi-zope.security-license = %{version}-%{release}
Requires: pypi-zope.security-filemap = %{version}-%{release}

%description lib
lib components for the pypi-zope.security package.


%package license
Summary: license components for the pypi-zope.security package.
Group: Default

%description license
license components for the pypi-zope.security package.


%package python
Summary: python components for the pypi-zope.security package.
Group: Default
Requires: pypi-zope.security-python3 = %{version}-%{release}

%description python
python components for the pypi-zope.security package.


%package python3
Summary: python3 components for the pypi-zope.security package.
Group: Default
Requires: pypi-zope.security-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(zope.security)
Requires: pypi(setuptools)
Requires: pypi(zope.component)
Requires: pypi(zope.i18nmessageid)
Requires: pypi(zope.interface)
Requires: pypi(zope.location)
Requires: pypi(zope.proxy)
Requires: pypi(zope.schema)

%description python3
python3 components for the pypi-zope.security package.


%prep
%setup -q -n zope.security-5.4
cd %{_builddir}/zope.security-5.4
pushd ..
cp -a zope.security-5.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663257471
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-zope.security
cp %{_builddir}/zope.security-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-zope.security/a0b53f43aab58b46bf79ba756c50771c605ab4c5 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-zope.security

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-zope.security/a0b53f43aab58b46bf79ba756c50771c605ab4c5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
