#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF2A968348913D1D8 (tseaver@palladion.com)
#
Name     : zope.security
Version  : 4.1.0
Release  : 3
URL      : https://pypi.debian.net/zope.security/zope.security-4.1.0.tar.gz
Source0  : https://pypi.debian.net/zope.security/zope.security-4.1.0.tar.gz
Source99 : https://pypi.debian.net/zope.security/zope.security-4.1.0.tar.gz.asc
Summary  : Zope Security Framework
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.security-python
Requires: Sphinx
Requires: coverage
Requires: nose
Requires: pytz
Requires: setuptools
Requires: zope.component
Requires: zope.configuration
Requires: zope.i18nmessageid
Requires: zope.interface
Requires: zope.location
Requires: zope.proxy
Requires: zope.schema
Requires: zope.testing
Requires: zope.testrunner
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : zope.i18nmessageid
BuildRequires : zope.interface
BuildRequires : zope.location
BuildRequires : zope.proxy
BuildRequires : zope.schema

%description
``zope.security``
=================
.. image:: https://img.shields.io/pypi/v/zope.security.svg
:target: https://pypi.python.org/pypi/zope.security/
:alt: Latest Version

%package python
Summary: python components for the zope.security package.
Group: Default

%description python
python components for the zope.security package.


%prep
%setup -q -n zope.security-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1493208403
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :
%install
export SOURCE_DATE_EPOCH=1493208403
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
